### ISSUE TITLE
Add contact info in case people want to contribute?

### ISSUE THREAD

**Issue by bramiozo** [umcu/clinlp#60]
Maybe a good idea to have something like: ```opensource@umcutrecht.nl``` ?

**Comment by vmenger** [comment]
Right, we listed analytics@umcutrecht.nl under contact info, where at least @msnackey and me can read. I guess an email account for open source would be nice, but we don't want to handle all open source work for the UMCU? 

Besides the contact info some better conbrituting guidelines and instructions on setting up the environment would be very helpful as well.
